version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: myapp-nginx
    ports:
      - '8901:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src:/var/www/html:rw,cached
      - ./certs:/etc/certs
    depends_on:
      - wordpress
    restart: always 

  mysql:
    image: mariadb
    container_name: myapp-mysql
    volumes:
       - './data/db:/var/lib/mysql:delegated'
    environment:
      - MYSQL_ROOT_PASSWORD="${DB_PASSWORD}"
      - MYSQL_DATABASE="${DB_NAME}"
    restart: always
    ports:
      - '3306:3306'

  wordpress:
    image: wordpress:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp-wordpress
    volumes:
      - ./src:/var/www/html:rw,cached 
      - ./theme-base:/var/www/html/wp-content/themes/theme-base
      - ./.env:/var/www/html/.env
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      - WORDPRESS_DB_NAME="${DB_NAME}"
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD="${DB_PASSWORD}"
    depends_on:
      - mysql
    # restart: always

 # phpmyadmin
  phpmyadmin:
    container_name: myapp-phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9001:80'
    environment:
      PMA_HOST: mysql
      MYSQL_USER: root 
      MYSQL_ROOT_PASSWORD: password 

  composer:
    image: composer/composer
    container_name: myapp-composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ./src:/var/www/html:rw,cached
